GRAPHRAG_LLM_API_URL: https://XXXXX.openai.azure.com/
GRAPHRAG_LLM_DEPLOYMENT: gpt-4o
GRAPHRAG_LLM_API_VERSION: 2024-05-01-preview
GRAPHRAG_LLM_API_KEY: XXXXXX
GRAPHRAG_EMBEDDING_API_URL: https://XXXX.openai.azure.com/
GRAPHRAG_EMBEDDING_API_KEY: XXXX
GRAPHRAG_EMBEDDING_DEPLOYMENT: text-embedding-3-small
GRAPHRAG_CLAIM_EXTRACTION_ENABLED: False
INPUT_DIR: "/Users/XXXX"
COMMUNITY_LEVEL: 2
