GRAPHRAG_LLM_API_URL: https://openai-hu-non-product-test.openai.azure.com/
GRAPHRAG_LLM_DEPLOYMENT: gpt-4o
GRAPHRAG_LLM_API_VERSION: 2024-05-01-preview
GRAPHRAG_LLM_API_KEY: 41433befdf824b348136ef86bb897073
GRAPHRAG_EMBEDDING_API_URL: https://openai-hu-non-product-test.openai.azure.com/
GRAPHRAG_EMBEDDING_API_KEY: 41433befdf824b348136ef86bb897073
GRAPHRAG_EMBEDDING_DEPLOYMENT: text-embedding-3-small
GRAPHRAG_CLAIM_EXTRACTION_ENABLED: False
INPUT_DIR: "/Users/huqianghui/doushen/ragtest/output/doushen/20241017-120057/artifacts"
COMMUNITY_LEVEL: 2
